version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.0

jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Build
          command: |
            HUGO_ENV=production hugo --destination /tmp/workspace/public
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - public
  deploy:
    docker:
      - image: circleci/python
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - aws-s3/sync:
          from: '/tmp/workspace/public'
          to: ' s3://igu.io'
          arguments: --acl public-read --cache-control "max-age=86400"
          overwrite: true

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          context: igu-io-production
          filters:
            branches:
              only: master
          requires:
            - build
