version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.1

jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Build
          command: |
            HUGO_ENV=production hugo --destination /tmp/workspace/public --templateMetrics --templateMetricsHints --minify
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - public
  deploy:
    docker:
      - image: circleci/python
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - aws-cli/install
      - aws-cli/configure:
          aws-region: eu-west-2
      - run:
          name: Deploy
          command: aws s3 sync public s3://igu.io

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          context: igu-io-production
          filters:
            branches:
              only: master
          requires:
            - build
